apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: py-github-quay
  janus-idp.io/tekton: py-github-quay
  backstage.io/kubernetes-id: py-github-quay
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-github-quay
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
